### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by xxia-kathy** [printablealice/a3#1]
`Scanning dependencies of target manip-app
[ 92%] Building CXX object src/app/CMakeFiles/manip-app.dir/manip-app.cpp.o
In file included from /Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/app/manip-app.cpp:11:
In file included from /Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Simulation.h:5:
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:17:21: error: implicit instantiation of undefined template 'std::__1::array<int, 3>'
        std::array<int, 3> nodeIndices; // the collection of nodes that define the triangle element
                           ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__tuple:223:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
In file included from /Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/app/manip-app.cpp:11:
In file included from /Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Simulation.h:5:
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:26:17: error: cannot initialize object parameter of type 'const Element' with an expression of type 'Triangle'
                Vector2d v1 = nodePos(1, X) - nodePos(0, X);
                              ^~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:26:33: error: cannot initialize object parameter of type 'const Element' with an expression of type 'Triangle'
                Vector2d v1 = nodePos(1, X) - nodePos(0, X);
                                              ^~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:27:17: error: cannot initialize object parameter of type 'const Element' with an expression of type 'Triangle'
                Vector2d v2 = nodePos(2, X) - nodePos(0, X); 
                              ^~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:27:33: error: cannot initialize object parameter of type 'const Element' with an expression of type 'Triangle'
                Vector2d v2 = nodePos(2, X) - nodePos(0, X); 
                                              ^~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:97:15: error: cannot initialize object parameter of type 'const Element' with an expression of type
      'const Triangle'
                return area(nodePos(1, x) - nodePos(0, x), nodePos(2, x) - nodePos(0, x));
                            ^~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:97:31: error: cannot initialize object parameter of type 'const Element' with an expression of type
      'const Triangle'
                return area(nodePos(1, x) - nodePos(0, x), nodePos(2, x) - nodePos(0, x));
                                            ^~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:97:46: error: cannot initialize object parameter of type 'const Element' with an expression of type
      'const Triangle'
                return area(nodePos(1, x) - nodePos(0, x), nodePos(2, x) - nodePos(0, x));
                                                           ^~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:97:62: error: cannot initialize object parameter of type 'const Element' with an expression of type
      'const Triangle'
                return area(nodePos(1, x) - nodePos(0, x), nodePos(2, x) - nodePos(0, x));
                                                                           ^~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:111:17: error: cannot initialize object parameter of type 'const Element' with an expression of type
      'const Triangle'
                Vector2d v1 = nodePos(1, x) - nodePos(0, x);
                              ^~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:111:33: error: cannot initialize object parameter of type 'const Element' with an expression of type
      'const Triangle'
                Vector2d v1 = nodePos(1, x) - nodePos(0, x);
                                              ^~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:112:17: error: cannot initialize object parameter of type 'const Element' with an expression of type
      'const Triangle'
                Vector2d v2 = nodePos(2, x) - nodePos(0, x);
                              ^~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Triangle.h:112:33: error: cannot initialize object parameter of type 'const Element' with an expression of type
      'const Triangle'
                Vector2d v2 = nodePos(2, x) - nodePos(0, x);
                                              ^~~~~~~
In file included from /Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/app/manip-app.cpp:11:
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Simulation.h:52:15: error: no matching member function for call to 'push_back'
                                triangles.push_back({ i_(r,     c    ), i_(r + 1, c    ), i_(r + 1, c + 1) });
                                ~~~~~~~~~~^~~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:705:36: note: candidate function not viable: cannot convert initializer list argument to 'const
      std::__1::__vector_base<std::__1::array<int, 3>, std::__1::allocator<std::__1::array<int, 3> > >::value_type' (aka 'const std::__1::array<int, 3>')
    _LIBCPP_INLINE_VISIBILITY void push_back(const_reference __x);
                                   ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:708:36: note: candidate function not viable: cannot convert initializer list argument to
      'std::__1::vector<std::__1::array<int, 3>, std::__1::allocator<std::__1::array<int, 3> > >::value_type' (aka 'std::__1::array<int, 3>')
    _LIBCPP_INLINE_VISIBILITY void push_back(value_type&& __x);
                                   ^
In file included from /Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/app/manip-app.cpp:11:
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Simulation.h:53:15: error: no matching member function for call to 'push_back'
                                triangles.push_back({ i_(r,     c    ), i_(r    , c + 1), i_(r + 1, c + 1) });
                                ~~~~~~~~~~^~~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:705:36: note: candidate function not viable: cannot convert initializer list argument to 'const
      std::__1::__vector_base<std::__1::array<int, 3>, std::__1::allocator<std::__1::array<int, 3> > >::value_type' (aka 'const std::__1::array<int, 3>')
    _LIBCPP_INLINE_VISIBILITY void push_back(const_reference __x);
                                   ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:708:36: note: candidate function not viable: cannot convert initializer list argument to
      'std::__1::vector<std::__1::array<int, 3>, std::__1::allocator<std::__1::array<int, 3> > >::value_type' (aka 'std::__1::array<int, 3>')
    _LIBCPP_INLINE_VISIBILITY void push_back(value_type&& __x);
                                   ^
In file included from /Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/app/manip-app.cpp:4:
In file included from /Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/guiLib/application.h:8:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/map:455:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__tree:15:
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1372:9: error: implicit instantiation of undefined template 'std::__1::array<int, 3>'
        ++__i;
        ^
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Simulation.h:58:32: note: in instantiation of member function 'std::__1::__wrap_iter<std::__1::array<int, 3>
      *>::operator++' requested here
                for (const auto &nodeIndices : triangles) {
                                             ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/__tuple:223:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
In file included from /Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/app/manip-app.cpp:11:
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Simulation.h:155:53: error: no matching member function for call to 'push_back'
                for (const auto &_ : triangles) { energy.elements.push_back(&_); }
                                                  ~~~~~~~~~~~~~~~~^~~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:705:36: note: candidate function not viable: no known conversion from 'const Triangle *' to 'const
      std::__1::__vector_base<const Element *, std::__1::allocator<const Element *> >::value_type' (aka 'const Element *const') for 1st argument
    _LIBCPP_INLINE_VISIBILITY void push_back(const_reference __x);
                                   ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/vector:708:36: note: candidate function not viable: no known conversion from 'const Triangle *' to 'std::__1::vector<const
      Element *, std::__1::allocator<const Element *> >::value_type' (aka 'const Element *') for 1st argument
    _LIBCPP_INLINE_VISIBILITY void push_back(value_type&& __x);
                                   ^
In file included from /Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/app/manip-app.cpp:11:
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Simulation.h:157:28: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
                if (energy.APPLY_GRAVITY = APPLY_GRAVITY) {
                    ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Simulation.h:157:28: note: place parentheses around the assignment to silence this warning
                if (energy.APPLY_GRAVITY = APPLY_GRAVITY) {
                                         ^
                    (                                   )
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Simulation.h:157:28: note: use '==' to turn this assignment into an equality comparison
                if (energy.APPLY_GRAVITY = APPLY_GRAVITY) {
                                         ^
                                         ==
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Simulation.h:160:29: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
                if (energy.SOLVE_DYNAMICS = SOLVE_DYNAMICS) {
                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Simulation.h:160:29: note: place parentheses around the assignment to silence this warning
                if (energy.SOLVE_DYNAMICS = SOLVE_DYNAMICS) {
                                          ^
                    (                                     )
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/femLib/Simulation.h:160:29: note: use '==' to turn this assignment into an equality comparison
                if (energy.SOLVE_DYNAMICS = SOLVE_DYNAMICS) {
                                          ^
                                          ==
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/app/manip-app.cpp:236:2: error: class member cannot be redeclared
        EIGEN_MAKE_ALIGNED_OPERATOR_NEW
        ^
/usr/local/include/eigen3/Eigen/src/Core/util/Memory.h:690:41: note: expanded from macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW'
#define EIGEN_MAKE_ALIGNED_OPERATOR_NEW EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(true)
                                        ^
/usr/local/include/eigen3/Eigen/src/Core/util/Memory.h:663:13: note: expanded from macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF'
      void *operator new(std::size_t size) { \
            ^
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/app/manip-app.cpp:20:9: note: previous definition is here
public: EIGEN_MAKE_ALIGNED_OPERATOR_NEW
        ^
/usr/local/include/eigen3/Eigen/src/Core/util/Memory.h:690:41: note: expanded from macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW'
#define EIGEN_MAKE_ALIGNED_OPERATOR_NEW EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(true)
                                        ^
/usr/local/include/eigen3/Eigen/src/Core/util/Memory.h:663:13: note: expanded from macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF'
      void *operator new(std::size_t size) { \
            ^
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/app/manip-app.cpp:236:2: error: class member cannot be redeclared
        EIGEN_MAKE_ALIGNED_OPERATOR_NEW
        ^
/usr/local/include/eigen3/Eigen/src/Core/util/Memory.h:690:41: note: expanded from macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW'
#define EIGEN_MAKE_ALIGNED_OPERATOR_NEW EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(true)
                                        ^
/usr/local/include/eigen3/Eigen/src/Core/util/Memory.h:666:13: note: expanded from macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF'
      void *operator new[](std::size_t size) { \
            ^
/Users/kathyxxj/Documents/animation/a3-xxia-kathy/src/app/manip-app.cpp:20:9: note: previous definition is here
public: EIGEN_MAKE_ALIGNED_OPERATOR_NEW
        ^
/usr/local/include/eigen3/Eigen/src/Core/util/Memory.h:690:41: note: expanded from macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW'
#define EIGEN_MAKE_ALIGNED_OPERATOR_NEW EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(true)
                                        ^
/usr/local/include/eigen3/Eigen/src/Core/util/Memory.h:666:13: note: expanded from macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF'
      void *operator new[](std::size_t size) { \
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
make[2]: *** [src/app/CMakeFiles/manip-app.dir/manip-app.cpp.o] Error 1
make[1]: *** [src/app/CMakeFiles/manip-app.dir/all] Error 2
make: *** [all] Error 2`

Hello,

I'm getting these make error on a MacOS Mojave, anyone know how I can fix it?

Thank you

**Comment by xxia-kathy** [comment]
I was able to make by commenting out

// public: EIGEN_MAKE_ALIGNED_OPERATOR_NEW in manip-app.cpp
and adding #include <array> in triangle.h

**Comment by tillns** [comment]
What did you include in Triangle.h?

**Comment by xxia-kathy** [comment]
Oops sorry didn't realize it doesn't show without wrapping in code mark up

`#include <array>`

**Comment by printablealice** [comment]
Hi!  Those still having this issue should be able to pull a fix now (NOTE: I do not have a Mac so I cannot test).

Added ```#include <array>``` in BernHelpers.h
Removed ```public: EIGEN_MAKE_ALIGNED_OPERATOR_NEW``` from Line 234 of manip-app.cpp
