### ISSUE TITLE
After adding regularizer the target cannot be reached

### ISSUE THREAD

**Issue by chaofiber** [printablealice/a3#12]
![Screenshot from 2020-04-20 17-23-19](https://user-images.githubusercontent.com/39195147/79768880-aac39c00-832b-11ea-80bc-d66f6395e9e0.png)
![Screenshot from 2020-04-20 17-22-34](https://user-images.githubusercontent.com/39195147/79768884-abf4c900-832b-11ea-8012-53d7abb59eb7.png)

Hello, just as shown in the pictures above. After I added the regularizer, the target point and the actual point doesn't match exactly. Although the problem of vertical soft bar is somehow solved, I am wondering is such case acceptable because we are know looking for sub optimal solution? Or any suggestions on how to deal with such problems generally?

Thanks,

**Comment by printablealice** [comment]
Yo!--Great question.  Note: I will assume you're happy with the objective and regularizer, and will talk generally about weighting.

So you're trading off between two subobjectives now, which is always going to be an imperfect balancing act.

All you can really do is tune the relative weight.

Let's say your objective is ```O = Q + w * R``` where ```Q``` is the main "reach the target" objective, and ```R``` is the reularizer.  Note: If you set ```w = 0``` then you're just left with ```Q```.  The weight ```w``` says how much you care about ```R```.  Maybe try something like ```1e-3```?--I usually use a slider to play around with the weighting.

Note: If you have a bunch of subobjectives then tuning your weights becomes quite challenging.  In our case it should be just fine :)

**Comment by printablealice** [comment]
Though to be clear, from the screenshot that looks like your answer would already get full credit 🙆‍♂️
