### ISSUE TITLE
Cannot click and move the handles or target points

### ISSUE THREAD

**Issue by ioanna21** [printablealice/a3#2]
When I click on the handles of the mesh, or on the target position points there is no response. If I click on another location above these points, then sometimes they move, but it is really hard to find that location. It is as if the control points are in a different location than the drawn points and handles on the window.

**Comment by sukhijab** [comment]
In addition to the issue posted above, for me the app is not the same as the one shown in the video. I do not have the option to manipulate log(k) for example.

**Comment by printablealice** [comment]
@ioanna21 Could you tell me what platform you're running on? Did you try setting I_AM_HAVING_SCREEN_ISSUES to true?

**Comment by printablealice** [comment]
@sukhijab Sorry I wasn't clear about that, the video shows a modified version of the app I made just for the video so I could explain pins.  I kept the version I gave to the class as minimal as possible so it would be easier to understand.

If you would like to manipulate log(k) just add something like this to ```process()```

```
for (auto &pin : sim.pins) { pin.k = pow(10., log_k) - 1.; }
```

**Comment by sukhijab** [comment]
I was also having the same issue and changing I_AM_HAVING_SCREEN_ISSUES to true didnt make a difference.
I am using macOS with the Xcode IDE.

Thanks

**Comment by printablealice** [comment]
Gotcha.  Sorry about that.  This will be somewhat challenging for me to debug remotely.

For now please add the following line to the end of ```drawNanoVG()``` which will show you where the program thinks the mouse is.

```{ auto push = CIRCLE_RADIUS; CIRCLE_RADIUS *= 3; NVGcolor c = GREEN; c.a = .7f; fillCircle(x_mouse, c); CIRCLE_RADIUS = push; }```

If you get a chance, send me a video of what you see and I will see if I can figure out what's going on (probably something needs to be multiplied or divided by 2.)

**Comment by printablealice** [comment]
Setting `bool I_AM_HAVING_SCREEN_ISSUES = true;` should now solve scaling issue for Retina screens.

Also added option to `DRAW_MOUSE_POSITION`.

**Comment by ioanna21** [comment]
Great, thanks for the answer! I'm using Windows, and now it works when I set I_AM_HAVING_SCREEN_ISSUES to true.
