### ISSUE TITLE
In addition to the issue posted above, for me the app is not the same as the one shown in the video. I do not have the option to manipulate log(k) for example.

### ISSUE THREAD

**Issue by printablealice** [printablealice/a3#3]
In addition to the issue posted above, for me the app is not the same as the one shown in the video. I do not have the option to manipulate log(k) for example.

_Originally posted by @sukhijab in https://github.com/printablealice/a3/issues/2#issuecomment-609002452_

**Comment by printablealice** [comment]
@sukhijab Sorry for the confusion, I could have been more clear.  The video shows a modified version of the app I made so I could explain pins.  I kept the version I gave to the class as minimal as possible so it would be easier to understand.

If you would like to manipulate log(k) just add something like this to ```process()```:

```
for (auto &pin : sim.pins) { pin.k = pow(10., log_k) - 1.; }
```

If you would like to draw the pins as red lines please add something like this to ```drawNanoVG()```:

```
sim.pushSimulationState(); {
    sim.updatePinAnchorsAccordingToHandles(sim.stackControl(get_handleTranslations(), 					 
   get_handleRotations()));
    for (const auto &pin : sim.pins) {
        connectDots({ pin.anchorPosition, pin.getPosition(sim.x) }, RED, 2.f);
    }
} sim.popSimulationState();
```

**Comment by sukhijab** [comment]
Thanks
