### ISSUE TITLE
clarification to manip-app.cpp

### ISSUE THREAD

**Issue by yannickkoster** [printablealice/a3#5]
Hello

What is the difference between o and xy (in terms of meaning and not value)?

**Comment by printablealice** [comment]
You need some way to propagate handle translation ```T``` and rotation ```theta``` to its pins.
I.e. for a given pin, how should we define ```p_prime(theta, T)```?
---
First let's just consider translation.
Call ```T``` the _handle translation_ (sometimes for convenience I write ```xy`` instead).
Consider one of that handle's pins, bound to node with rest position ```s_X```. 
A logical choice would be ```p_prime = s_x + T```
---
Now let's add in rotation.
Call ```theta``` the _handle translation_.
This raises the question, _What point are we rotating about?_
I call that point ```o```, the _handle center_.
It choose it in the constructor, and never change it again (i.e. it is constant, like ```s_X```).
It doesn't really matter which point you choose ```o``` to be, but you do need to pick _something_.  Feel free to try something else.
Anyway, the above discussion can be written succinctly as the ```p_prime = o + rotate_(from_(o, s_X), theta) + T;``` you see in ```updatePinAnchorsAccordingToHandles``` :)

I.e. in order to calculate ```p_prime(theta, T)```...

Start at ```o```, add on the vector from ```o -> s_X``` (only rotated by ```theta```), and finally translate by ```T```.

**Comment by yannickkoster** [comment]
Thanks for the explanation in detail! I understand the logic now :)

**Comment by printablealice** [comment]
No problem!--Thanks for the question :)
