### ISSUE TITLE
NotImplementedWarning:get_dOdx

### ISSUE THREAD

**Issue by Bombenchris** [printablealice/a3#6]
Why It keeps reporting error NotImplementedWarning:get_dOdx,
even though I implemented dOdx??
https://github.com/printablealice/a3/blob/19f656ddb301f9c9ed231d66893b954dc27b0114/src/app/manip-app.cpp#L132-L141

**Comment by printablealice** [comment]
Hi, thanks for the question!

That was just so you knew that I'd left that particular function unimplemented for you to finish.

Once you have implemented it, please feel free to delete the line

```cout << "NotImplementedWarning:get_dOdx" << endl;```
